#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
from setuptools import find_packages
setup_params = dict(
	name='popquotes',
	use_hg_version=True,
	packages=find_packages(),
	namespace_packages=[''],
	zip_safe=False,
	install_requires=[
		'pmxbot>=1100',
	],
	setup_requires=[
		'hgtools',
	],
	entry_points = dict(
		pmxbot_handlers = [
			'popular_quotes = popquotes.pmxbot:install_commands',
		],
	),
)
if __name__ == '__main__':
	from setuptools import setup
	setup(**setup_params)
